name: Build Docker image for integration testing

on:
  push:
    inputs:
      docker_tag:
        description: The tag for the built docker image
        required: true
      args:
        description: Args to pass to `cargo build`, e.g. --features=runtime-benchmarks
        default: ''
        required: false

jobs:
  main:
    name: Push Integritee Node to Dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes on ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build docker image
        run: |
          ./scripts/build-docker.sh latest
          echo "============================="
          docker images
      
      - name: login in docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push docker image
        run: |
          docker push litentry/integritee-node:latest

      - name: Remove dangling images if any
        run: |
          [ -z "$(docker images --filter=dangling=true -q)" ] || docker rmi -f $(docker images --filter=dangling=true -q)

      - name: Copy client binary to disk
        run: |
          docker cp $(docker create --rm litentry/integritee-node:latest):/usr/local/bin/integritee-node .

      - name: Upload the client binary
        uses: actions/upload-artifact@v2
        with:
          name: integritee-node
          path: |
            integritee-node
