name: Build Docker image for integration testing

on:
  push:

jobs:
  main:
    name: Push Integritee Node to Dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes on ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.MANTABOT_DOCKER_USERNAME }}
          password: ${{ secrets.MANTABOT_DOCKER_TOKEN }}

      - name: Build and push
        id:   docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: |
            integritee/${{ matrix.binary }}:latest
            integritee/${{ matrix.binary }}:${{ github.event.release.tag_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

